name: twelve_notes
description: "An app to play your favourite songs with lyrics and chords"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/sen/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sen/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/sen/Sen-Regular.ttf
          weight: 400
    - family: Viga
      fonts:
        - asset: assets/fonts/viga/Viga-Regular.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Bold.ttf
          weight: 900
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Italic.ttf
          style: italic
