name: twelve_notes
description: "An app to play your favourite songs with lyrics and chords"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  sign_button: ^2.0.6
  supabase_flutter: ^2.6.0
  talker: ^4.3.2
  talker_bloc_logger: ^4.3.2
  window_manager: ^0.4.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  data_fixture_dart: ^2.2.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/sen/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sen/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/sen/Sen-Regular.ttf
          weight: 400
    - family: Viga
      fonts:
        - asset: assets/fonts/viga/Viga-Regular.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Bold.ttf
          weight: 900
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Italic.ttf
          style: italic
